# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  simulation:
    restart: unless-stopped
    healthcheck:
      test: >
        curl -f -X GET http://localhost:8080/health || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    build:
      context: ./
      target: production
    environment:
      RABBITMQ_URL: amqp://simulation-rabbitmq:5672
      PAYMENT_URL: http://payment:8080
      SHIPMENT_URL: http://shipment:8080
    depends_on:
      - simulation-rabbitmq
  simulation-rabbitmq:
    image: "rabbitmq:3-management"
  simulation-dapr:
    image: "daprio/daprd:edge"
    network_mode: "service:simulation"
    command:
      [
        "./daprd",
        "--app-id",
        "payment",
        "--app-port",
        "${EXPERIMENT_CONFIG_SIDECAR_PORT:-8080}",
        "--dapr-http-port",
        "3500",
        "-placement-host-address",
        "placement:50006",
        "--config",
        "/config.yaml",
        "--resources-path",
        "/components",
      ]