services:
  simulation:
    extends:
      file: docker-compose-base.yaml
      service: simulation
    ports:
      - 8080:8080
    build:
      context: ./
      target: development
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container src/app
    # reflect file changes from host to container
    volumes:
      - .:/src/simulation
      - /src/simulation/node_modules
    command: npm run start:dev
  simulation-rabbitmq:
    extends:
      file: docker-compose-base.yaml
      service: simulation-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


    